language: c
sudo: required
services:
  - docker
script: bash -ex .travis-ci.sh
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.00.1
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.02.3 COVERAGE=true
matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.00.1
