platform:
    - x86

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_MIRROR: http://cygwin.uib.no
        CYG_CACHE: C:/cygwin/var/cache/setup
    matrix:
        - 
            CYG_ARCH: x86

init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P wget  -P dos2unix -P diffutils -P cpio -P make -P patch -P mingw64-i686-gcc-core -P mingw64-i686-gcc-g++ >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
    - '%CYG_ROOT%/bin/bash -lc "wget -q http://ml.ignorelist.com/wodi/7/wodi32.tar.xz -O /tmp/wodi32.tar.xz"'
    - '%CYG_ROOT%/bin/bash -lc "cd /tmp && rm -rf wodi32 && tar -xf wodi32.tar.xz && bash wodi32/install.sh"'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor/build.sh"'

artifacts:
  - path: test.log
    name: test-logs
