os: unstable

platform:
    - x64

environment:
    global:
        CYG_ARCH: x86
        CYG_ROOT: C:/cygwin
    matrix:
        -   WODI_ARCH: 32
            MINGW_ARCH: i686
        -   WODI_ARCH: 64
            MINGW_ARCH: x86_64

init:
    - 'echo System architecture: %PLATFORM%'
    - appveyor DownloadFile "http://wodi.forge.ocamlcore.org/wodi%WODI_ARCH%.tar.xz" -FileName "C:/wodi%WODI_ARCH%.tar.xz"

install:
    - if not exist "%CYG_ROOT%" mkdir "%CYG_ROOT%"
    - appveyor DownloadFile "http://cygwin.com/setup-%CYG_ARCH%.exe" -FileName "%CYG_ROOT%\setup.exe"
    - '"%CYG_ROOT%\setup.exe" -qnBWNd -R "%CYG_ROOT%" -P cygwin -P wget  -P dos2unix -P diffutils -P cpio -P make -P patch -P mingw64-%MINGW_ARCH%-gcc-core -P mingw64-%MINGW_ARCH%-gcc-g++ >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor/install.sh %WODI_ARCH% %MINGW_ARCH% wodi%WODI_ARCH%.tar.xz"'

build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor/build.sh %WODI_ARCH%"'

artifacts:
  - path: test.log
    name: test-logs
