name: Ctypes
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [ '4.09.0', '4.10.0' ]
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@v1.0
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Deps
      run: |
        opam pin add -n ctypes.dev .
        opam pin add -n ctypes-foreign.dev .
        opam depext -ty ctypes ctypes-foreign
        opam install -t --deps-only .
    - name: Build
      run: opam exec -- make
    - name: Test
      run: opam exec -- make test
