name: Ctypes

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ocaml-version: 4.02.3
          - os: ubuntu-latest
            ocaml-version: 4.03.0
          - os: ubuntu-latest
            ocaml-version: 4.04.0
          - os: ubuntu-latest
            ocaml-version: 4.05.0
          - os: ubuntu-latest
            ocaml-version: 4.06.0
          - os: ubuntu-latest
            ocaml-version: 4.07.0
          - os: ubuntu-latest
            ocaml-version: 4.08.0
          - os: ubuntu-latest
            ocaml-version: 4.09.0
          - os: ubuntu-latest
            ocaml-version: 4.10.0+flambda
          - os: ubuntu-latest
            ocaml-version: 4.11.1
          - os: ubuntu-latest
            ocaml-version: 4.12.0
          - os: windows-latest
            ocaml-version: 4.11.1
          - os: windows-latest
            ocaml-version: 4.12.0
          - os: macos-latest
            ocaml-version: 4.11.1
          - os: macos-latest
            ocaml-version: 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Deps
        run: |
          opam pin add -n ctypes.dev .
          opam pin add -n ctypes-foreign.dev .
          opam depext -ty ctypes ctypes-foreign
          opam install -t --deps-only .

      - name: Build
        run: opam exec -- make

      - name: Test
        run: opam exec -- make test

      - name: Test inverted stubs
        run: opam pin add -n ctypes-inverted-stubs-example https://github.com/yallop/ocaml-ctypes-inverted-stubs-example.git 
